### ISSUE TITLE
Update instructions and perhaps add Tip Jar?

### ISSUE THREAD

**Issue by interactiveRob** [layflags/rolling-number#1]
Woah! It was so hard to find an open source tool to accomplish the rolling numbers animation. Your CustomElement work made it easy to implement with no issues.

You should add a tip jar to your readme like https://www.buymeacoffee.com, I want to contribute.

Also I was able to figure out by looking at the demo that I just needed to manipulate the value attribute when I want the animation to start, but that may not be clear to others. 

I might make a PR on the readme to help you update the instructions there. Thanks! 

Feel free to close the issue after reading.

**Comment by layflags** [comment]
Thank you so much for your feedback @interactiveRob 🙏 I added a buymeacoffee button to the README. Feel free to open a PR to improve the documentation.

https://buymeacoffee.com/layflags
